### COMPANY OVERVIEW
#### PROJECT OVERVIEW
#### BUSINESS PROBLEM
#### BUSINESS IMPACT
#### PROJECT OBJECTIVE

In [ ]:
# Import Libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [ ]:
# Load Raw Dataset
df = pd.read_csv(r"C:\Users\earlc\Amdari\Week 2\nexora_care_flow\data\raw\AppointmentRecords.csv")

In [10]:
# Inspect First 5 Rows
df.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False

In [12]:
# Inspect Last 5 Rows
df.tail()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
129348,629350,4,Nexora Care - Hillcrest,Primary Care,105879,405,2025-12-31 16:30,Follow-Up,Completed,Online,12,True,New Year's Eve,Flu Season,False
129349,529373,1,Nexora Care - Riverside,Primary Care,101403,102,2025-12-31 16:30,Follow-Up,Completed,Online,7,True,New Year's Eve,Flu Season,True
129350,529376,1,Nexora Care - Riverside,Primary Care,101248,106,2025-12-31 16:30,Urgent,Completed,Online,2,True,New Year's Eve,Flu Season,False
129351,629337,4,Nexora Care - Hillcrest,Primary Care,106370,406,2025-12-31 16:45,Urgent,Completed,Online,1,True,New Year's Eve,Flu Season,False
129352,575056,2,Nexora Care - Lakeside,Multi-Specialty,102543,206,2025-12-31 17:45,Telehealth,Cancelled,Phone,10,True,New Year's Eve,Flu Season,True

In [14]:
# Dataset Shape
df.shape

(129353, 15)

In [15]:
# Data Types & Column Summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  str
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           939 non-null     str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), int64(5), str(8)
memory usage: 13.1 MB

In [16]:
# Summary Statistics
df.describe()

,AppointmentID,ClinicID,PatientID,ProviderID,BookingLeadTimeDays
count,129353.000000,129353.000000,129353.000000,129353.000000,129353.000000
mean,564676.000000,2.417864,103553.485385,245.290005,8.704267
std,37341.139023,1.071525,2020.941152,107.165883,7.641921
min,500000.000000,1.000000,100000.000000,101.000000,0.000000
25%,532338.000000,2.000000,101812.000000,201.000000,3.000000
50%,564676.000000,2.000000,103547.000000,205.000000,7.000000
75%,597014.000000,3.000000,105178.000000,306.000000,12.000000
max,629352.000000,4.000000,107279.000000,406.000000,60.000000

In [17]:
# Missing Values Audit
df.isnull().sum()

AppointmentID                0
ClinicID                     0
ClinicName                   0
ClinicType                   0
PatientID                    0
ProviderID                   0
AppointmentDateTime          0
AppointmentType              0
Status                       0
BookingChannel               0
BookingLeadTimeDays          0
IsHoliday                    0
HolidayName             128414
SeasonFlag                   0
ChronicConditionFlag         0
dtype: int64

In [18]:
# Unique Values Count
df.nunique()

AppointmentID           129353
ClinicID                     4
ClinicName                   4
ClinicType                   3
PatientID                 7109
ProviderID                  24
AppointmentDateTime      30287
AppointmentType              4
Status                       4
BookingChannel               4
BookingLeadTimeDays         61
IsHoliday                    2
HolidayName                 13
SeasonFlag                   3
ChronicConditionFlag         2
dtype: int64

In [25]:
# Impute Missing HolidayName Values
df['HolidayName'] = df['HolidayName'].fillna('None')

# Remaining Missing Values after Holiday Imputation
df.isnull().sum()

AppointmentID           0
ClinicID                0
ClinicName              0
ClinicType              0
PatientID               0
ProviderID              0
AppointmentDateTime     0
AppointmentType         0
Status                  0
BookingChannel          0
BookingLeadTimeDays     0
IsHoliday               0
HolidayName             0
SeasonFlag              0
ChronicConditionFlag    0
dtype: int64

In [26]:
# Check for Duplicates
df.duplicated().sum()

np.int64(0)

In [30]:
# Parse AppointmentDateTime to datetime object
df['AppointmentDateTime'] = pd.to_datetime(df['AppointmentDateTime'])

# Inspect AppointmentDateTime Column Info
df[['AppointmentDateTime']].info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   AppointmentDateTime  129353 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 1010.7 KB

In [36]:
# Export Cleaned Record-Level Dataset to Processed Folder
df.to_csv(
    r"C:\Users\earlc\Amdari\Week 2\nexora_care_flow\data\processed\cleaned_appointments.csv",
    index=False
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  datetime64[us]
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           129353 non-null  str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), datetime64[us](1), int64(5), str(7)
memory usage: 13.1 MB

In [37]:
df.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30:00,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30:00,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45:00,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45:00,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False